social/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^signup/$', views.SignupView.as_view(), name='signup'),
    url(r'^signin/$', views.SigninView.as_view(), name='signin'),
    url(r'^signout/$', views.SignoutView.as_view(), name='signout'),
    url(r'^(?P<username>\w+)/block/$', views.block, name="block-user"),
    url(r'^commend/$', views.commend, name="commend-post"),
    url(r'^comment/$', views.comment, name="comment-post"),
    url(r'^(?P<username>\w+)/add/$', views.add_friend, name="send-friend-request"),
    url(r'^(?P<username>\w+)/accept/$', views.accept, name="accept-friend-request"),
    url(r'^(?P<username>\w+)/ignore/$', views.refuse, name="ignore-friend-request"),
    url(r'^(?P<username>\w+)/cancel/$', views.cancel, name="cancel-friend-request"),
    url(r'^(?P<username>\w+)/$', views.UserView.as_view(), name="user-page"),
    url(r'^(?P<username>\w+)/people/$', views.PeopleView.as_view(), name='people'),
    url(r'^(?P<username>\w+)/people/block$', views.BlockListView.as_view(), name='block-list'),
    url(r'^(?P<username>\w+)/(?P<post_id>[0-9]+)/$', views.PostView.as_view(), name="post-detail"),
]

temu/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('social.urls', namespace='social'))
]

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Temu{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'user-page-style.css' %}" />
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <script src="{% static 'bower_components/js-cookie/src/js.cookie.js' %}"></script>
    {% block scripts %}
    {% endblock %}
</head>
<body>
    {% block body %}
    {% endblock %}
</body>

templates/comments.html
{% load staticfiles %}

{% if comments %}
    {% for comment in comments %}
        <div class="comment">
            <div class="comment-header">
                <span class="comment-header-author">
                {% if user.username == comment.author.username %}
                    You
                {% else %}
                    {{ comment.author.display_name }}
                {% endif %}
                </span>
                <span class="comment-header-timestamp">
                    {{ comment.post_time }}
                </span>
            </div>
            <div class="comment-text">{{ comment.post_text }}</div>
            <div class="comment-footer">
                <div id="{{ comment.id }}-commendations" class="commendations">
                    <span id="{{ comment.id }}-commendation-count">{{ comment.commendations.count }}</span>
                    {% if comment.commendations.count > 1%}
                        users likes
                    {% else %}
                        user like
                    {% endif %}
                    this post.
                </div>
                {%  if not user in comment.commendations.all %}
                    <span id="{{ comment.id }}-commends" class="commends" data-postid="{{ comment.id }}">
                        Commend
                    </span>
                {% endif %}
            </div>
        </div>
    {% endfor %}
{% else %}
    <span>Failed to retrieve comments.</span>
{% endif %}

templates/index.html
{% extends "base.html" %}

{% block body %}
    <div id="banner" class="container">
        <h1><a href="/">Temu</a></h1>
        <h2>Meet and connect with people around the globe</h2>
    </div>

    {% block content %}
        <div class="container">
            {% if user.is_authenticated %}
                <a href="signout/">Sign out</a>
            {%  else %}
                <a href="signin/">Sign in</a>
            {% endif %}
            <a href="signup/">Sign up</a>
        </div>
    {% endblock %}
{% endblock %}

templates/people.html
{% extends "user.html" %}

{% block main %}
<div>
    <form>{% csrf_token %}
        {{ form }}
        <input type="submit" value="Search" />
    </form>

    {% if people %}
        <div class="people">
            <div class="container-fluid">
                {% for person in people %}
                    <div class="person row">
                        <a href="{% url "social:user-page" person.username %}">{{ person.display_name }}</a>

                        <div class="btn-group pull-right" role="group" aria-label="actions">
                            <button type='button' class="friend-add-button btn btn-default" aria-label="Send Friend Request" data-href="{% url "social:send-friend-request" user.username %}" data-username="{{ person.username }}" {% if person in user.relationship.friends %}disabled{% endif %}>
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add
                            </button>
                            <button type='button' class="block-button btn btn-default" aria-label="Block Person" data-href="{% url 'social:block-user' user.username %}" data-username="{{ person.username }}">
                                <span class="glyphicon glyphicon-ban-circle" aria-hidden="true"></span> Block
                            </button>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}

    {% if blocked_user_list %}
        <div class="blocked-user-list">
            <div class="container-fluid">
                {% for person in blocked_user_list %}
                    <div class="person row">
                        <a href="{% url "social:user-page" person.username %}">{{ person.display_name }}</a>

                        <div class="btn-group pull-right" role="group" aria-label="actions">
                            <button type='button' class="unblock-button btn btn-default" aria-label="Send Friend Request" data-href="{% url "social:send-friend-request" user.username %}" data-username="{{ person.username }}" {% if person in user.relationship.friends %}disabled{% endif %}>
                                <span class="glyphicon glyphicon-ok-circle" aria-hidden="true"></span> Unblock
                            </button>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}


    {% if request_list %}
        <div class="container-fluid">
        {% for friend_request in request_list %}
            <div>
            {{ friend_request.sender.display_name }} <button class="friend-accept-button">Accept</button>
            </div>
        {% endfor %}
        </div>
    {% endif %}

    {% if friend_list %}
        <div id="friend-list" class="container-fluid">
        {% for friend in friend_list %}
            {{ friend.display_name }}
        {% endfor %}
        </div>
    {% endif %}

    <a href="{% url "social:block-list" user.username %}">Blocked</a>
</div>
{% endblock %}

templates/signin.html
{% extends "index.html" %}

{% block content %}
    <div class="container">
        <form method="post">{% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Confirm" />
        </form>
    </div>
{% endblock %}

templates/signup.html
{% extends "index.html" %}

{% block content %}
    <div class="container">
        <form method="post">{% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="Submit" value="Confirm" />
        </form>
    </div>
{% endblock %}

templates/user.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}{{ user.username }}{% endblock %}

{% block scripts %}
    <script src="{% static "autosize.min.js" %}"></script>
    <script src="{% static "user-page.js" %}"></script>
{% endblock %}

{% block body %}

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Temu</a>
            </div>
            <div id="main-navbar-collapse" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    {% block navbar %}
                        <li><a href="#">Account</a></li>
                        <li><a href="{% url "social:people" username=user.username %}">People</a></li>
                        <li><a href="/signout/">Sign out <span class="sr-only">(current)</span></a></li>
                    {% endblock %}
                </ul>
            </div>
        </div>
    </nav>

    <div id="container">
        <div id="sidebar" class="col-md-2">
            {% block sidebar %}
                {% if page_user %}
                    <div id="profile">
                        <div>
                            <h3>{{ page_user.display_name }}<br/><small>{{ page_user.username }}</small></h3>
                        </div>

                        {% if page_user != user %}
                            <div class="btn-group" role="group" aria-label="actions">
                                <button type='button' class="friend-add-button btn btn-default" data-userid="{{ page_user.id }}">
                                    <span class="glyphicon glyphicon-plus" aria-hidden=true></span> Add
                                </button>
                                <button type='button' class="block-button btn btn-default" data-url="{% url 'social:block-user' request.user.username %}" data-username="{{ page_user.username }}">
                                    <span class="glyphicon glyphicon-ban-circle" aria-hidden="true"></span> Block
                                </button>
                            </div>
                        {% endif %}
                    </div>
                {% endif %}
            {% endblock %}
        </div>

        <div id="main" class="col-md-8">
        {% block main %}
            <div id="wall">
                {% if page_user == user %}
                <div>
                    <form method="post">{%  csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Post" />
                    </form>
                </div>
                {% endif %}

                {% if posts %}
                    <div id="posts">
                        {% for post in posts %}
                            {% if post.parent  %}
                            <div>
                                <div class="post-header">
                                    <span class="post-header-author">
                                    {% if user.username == post.parent.author.username %}
                                        You
                                    {% else %}
                                        {{ post.parent.author.display_name }}
                                    {% endif %}
                                    </span>
                                    <span class="post-header-timestamp">
                                        {{ post.parent.post_time }}
                                    </span>
                                </div>
                                <div>{{ post.parent.post_text }}</div>
                                <div>
                            {% endif %}
                                <div class="post">
                                <div class="post-header">
                                    <span class="post-header-author">
                                    {% if user.username == post.author.username %}
                                        You
                                    {% else %}
                                        {{ post.author.display_name }}
                                    {% endif %}
                                    </span>
                                    <span class="post-header-timestamp">
                                        {{ post.post_time }}
                                    </span>
                                </div>
                                <div class="post-text">{{ post.post_text }}</div>
                                <div class="post-footer">
                                    <div id="{{ post.id }}-commendations" class="commendations">
                                        <span id="{{ post.id }}-commendation-count">{{ post.commendations.count }}</span>
                                        {% if post.commendations.count > 1%}
                                            users likes
                                        {% else %}
                                            user like
                                        {% endif %}
                                        this post.
                                    </div>
                                    {%  if not user in post.commendations.all %}
                                        <span id="{{ post.id }}-commends" class="commends" data-postid="{{ post.id }}">
                                            Commend
                                        </span>
                                    {% endif %}
                                </div>
                                <div class="post-comments">
                                    <div id="{{ post.id }}-comment" class="comment-input container">
                                        <textarea id="{{ post.id }}-comment-input" row="2"></textarea>
                                        <input class="comment-submit" type="button" value="Post" data-postid="{{ post.id }}" data-csrftoken="{{ csrf_token }}"/>
                                    </div>
                                    <div id="{{ post.id }}-comments">
                                        {% for comment in comments %}
                                            {% if comment.post == post %}
                                                <div class="comment">
                                                    <div class="comment-header">
                                                        <span class="comment-header-author">
                                                        {% if user.username == comment.author.username %}
                                                            You
                                                        {% else %}
                                                            {{ comment.author.display_name }}
                                                        {% endif %}
                                                        </span>
                                                        <span class="comment-header-timestamp">
                                                            {{ comment.post_time }}
                                                        </span>
                                                    </div>
                                                    <div class="comment-text">{{ comment.post_text }}</div>
                                                    <div class="comment-footer">
                                                        <div id="{{ comment.id }}-commendations" class="commendations">
                                                            <span id="{{ comment.id }}-commendation-count">{{ comment.commendations.count }}</span>
                                                            {% if comment.commendations.count > 1%}
                                                                users likes
                                                            {% else %}
                                                                user like
                                                            {% endif %}
                                                            this post.
                                                        </div>
                                                        {%  if not user in comment.commendations.all %}
                                                            <span id="{{ comment.id }}-commends" class="commends" data-postid="{{ comment.id }}">
                                                                Commend
                                                            </span>
                                                        {% endif %}
                                                    </div>
                                                </div>
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                            {% if post.parent %}
                                </div>
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            {% endblock %}
        </div>
    </div>
{% endblock %}